@Todolist.Api_HostAddress = http://localhost:8080

### GET ALL
GET {{Todolist.Api_HostAddress}}/todos
Accept: application/json

### CREATE
POST {{Todolist.Api_HostAddress}}/todos
content-type: application/json

{
  "name": "Tarefa menos importante",
  "description": "Separa os documentos para o deposito",
  "done": false,
  "priority": 3
}

### UPDATE
PUT {{Todolist.Api_HostAddress}}/todos
content-type: application/json

{
   "id": 1,
  "name": "Tarefa mais importante",
  "description": "Concluir o projeto até o final do mês de abril",
  "done": false,
  "priority": 1
}

### DELETE
DELETE {{Todolist.Api_HostAddress}}/todos/2